leftnav:
- identifier: 3e5e4a5c-515e-3c68-e4e8-002cb2270fda
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: 25a79765-9be8-d955-c699-c42e26d36b68
  name: Calendar
  url: /pages/calendar
  weight: 20
- identifier: 9cd54542-9af7-b8e5-1429-ebe268c359eb
  name: Instructor Insights
  url: /pages/instructor-insights/
  weight: 30
- identifier: d67fd7d1-4643-b70e-c486-643c40f64013
  name: Addressing Communication in Mathematics through Recitations
  parent: 9cd54542-9af7-b8e5-1429-ebe268c359eb
  url: /pages/instructor-insights/developing-the-recitations
  weight: 40
- identifier: ed24c1d7-81e2-537b-d5c0-67e77d643bca
  name: Creating the Term Paper Assignment
  parent: 9cd54542-9af7-b8e5-1429-ebe268c359eb
  url: /pages/instructor-insights/creating-the-term-paper-assignment
  weight: 50
- identifier: 3156858d-7740-7520-8e55-2dbbe37cfe24
  name: Assessing Students' Writing
  parent: 9cd54542-9af7-b8e5-1429-ebe268c359eb
  url: /pages/instructor-insights/assessing-students-writing
  weight: 60
- identifier: 9a763fe0-e59f-409f-b79a-803366095f7c
  name: Lecture Notes
  url: /pages/lecture-notes
  weight: 70
- identifier: 158af2ca-df0b-75a7-a0ac-c3d65c8e80a1
  name: Recitations
  url: /pages/recitations
  weight: 80
- identifier: da91eead-061b-bf72-403e-0541333c7a07
  name: Assignments
  url: /pages/assignments
  weight: 90
- identifier: aceb9a38-5afa-b784-4f29-eae4479fb028
  name: Exams
  url: /pages/exams
  weight: 100
- identifier: 905d4790-2adb-1c3c-4fce-7cbc62f33659
  name: Writing Resources
  url: /pages/writing-resources
  weight: 110
